#!/usr/bin/env python3
"""
doc-layout-analyzer 训练脚本

用法（直接跑，或通过 run_tmux.py 调用）：
  python scripts/train_yolo.py \
      --data-dir ./data/yolo_dataset \
      --epochs 100 \
      --batch 16 \
      --model-size m
"""
import argparse
import os
import sys
import shutil
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


# ── 依赖检查 ──────────────────────────────────────────────────────────────────

def check_dependencies():
    errors = []
    try:
        import ultralytics
        print(f"  ✓ ultralytics {ultralytics.__version__}")
    except ImportError:
        errors.append("  ✗ ultralytics 未安装：pip install ultralytics")

    try:
        import torch
        cuda = torch.cuda.is_available()
        print(f"  ✓ PyTorch {torch.__version__}" +
              (" (CUDA)" if cuda else " (CPU only)"))
    except ImportError:
        errors.append("  ✗ PyTorch 未安装：pip install torch")

    if errors:
        print("\n依赖检查失败：")
        for e in errors:
            print(e)
        print("\n安装命令：")
        print("  pip install ultralytics torch --index-url https://download.pytorch.org/whl/cpu")
        sys.exit(1)


# ── 数据集准备 ────────────────────────────────────────────────────────────────

def prepare_dataset(data_root: Path) -> Path:
    """
    验证/生成 YOLO 格式数据集的 data.yaml
    期望目录结构：
      data_root/
        images/
          train/   ← 训练图片
          val/     ← 验证图片
        labels/
          train/   ← 同名 .txt（YOLO 格式）
          val/
        data.yaml ← 自动生成
    """
    if not data_root.exists():
        print(f"✗ 数据目录不存在: {data_root}")
        print("\n请先准备标注数据：")
        print("  1. 用 Label-Studio 标注论文 PDF")
        print("  2. 导出 JSON 后用 label_converter.py 转换：")
        print(f"     python scripts/label_converter.py --input annotations.json --output {data_root} --to-yolo")
        sys.exit(1)

    # 自动生成 data.yaml
    classes = [
        "title", "header", "body",
        "figure", "caption", "table",
        "footnote", "equation",
    ]

    yaml_content = f"""# Auto-generated by train_yolo.py
path: {data_root.resolve()}
train: images/train
val: images/val

nc: {len(classes)}
names: {classes}
"""

    yaml_path = data_root / "data.yaml"
    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    # 检查必要子目录
    for sub in ["images/train", "labels/train"]:
        if not (data_root / sub).exists():
            print(f"✗ 缺少目录: {data_root / sub}")
            sys.exit(1)

    # 统计图片数
    train_imgs = list((data_root / "images/train").glob("*.jpg")) + \
                  list((data_root / "images/train").glob("*.png"))
    val_imgs   = list((data_root / "images/val").glob("*.jpg")) + \
                  list((data_root / "images/val").glob("*.png"))

    print(f"  ✓ 数据集目录 : {data_root}")
    print(f"  ✓ 训练图片   : {len(train_imgs)} 张")
    print(f"  ✓ 验证图片   : {len(val_imgs)} 张")
    print(f"  ✓ 类别       : {classes}")
    print(f"  ✓ data.yaml  : {yaml_path}")

    return yaml_path


# ── 训练 ─────────────────────────────────────────────────────────────────────

def train(data_yaml: str, model_size: str = "m",
          epochs: int = 100, batch: int = 16,
          resume_path: str = None):
    """启动 YOLO 训练"""
    from ultralytics import YOLO

    print(f"\n{'='*50}")
    print(f"  模型     : yolov8{model_size}")
    print(f"  数据集   : {data_yaml}")
    print(f"  epochs   : {epochs}")
    print(f"  batch    : {batch}")
    print(f"{'='*50}\n")

    # 加载模型：从预训练权重开始（比从 yaml 初始化效果好）
    if resume_path and Path(resume_path).exists():
        print(f"从检查点恢复: {resume_path}")
        model = YOLO(resume_path)
    else:
        # 自动下载预训练权重（首次运行会下载 ~50MB）
        print("加载预训练权重 yolov8m.pt（首次会自动下载）...")
        model = YOLO("yolov8m.pt")

    # 开始训练
    results = model.train(
        data=data_yaml,
        epochs=epochs,
        batch=batch,
        imgsz=640,
        patience=10,           # 早停：10个epoch没提升就停
        save=True,
        save_period=max(5, epochs // 10),  # 每 N 个 epoch 保存一次
        project=str(ROOT / "runs" / "detect"),
        name="layout_model",
        exist_ok=True,         # 覆盖已有输出
        optimizer="AdamW",
        lr0=0.001,
        lrf=0.01,
        warmup_epochs=3,
        mosaic=0.5,
        mixup=0.1,
        close_mosaic=10,       # 后 N 个 epoch 关闭 mosaic 增强
        workers=4,
        # 自动选择设备（优先 GPU）
        device="0" if os.path.exists("/dev/nvidia0") else "cpu",
        verbose=True,
        seed=42,
        # 关闭 YOLO 的自动下载（用我们自己的 data.yaml）
        pretrained=True,
    )

    # ── 保存最终模型到 models/ ───────────────────────────────────────────
    run_dir = ROOT / "runs" / "detect" / "layout_model"
    best_pt = run_dir / "weights" / "best.pt"
    last_pt = run_dir / "weights" / "last.pt"
    models_dir = ROOT / "models"
    models_dir.mkdir(exist_ok=True)
    out_model = models_dir / f"layout_yolov8{model_size}.pt"

    if best_pt.exists():
        shutil.copy(best_pt, out_model)
        print(f"\n✓ 最佳模型已保存: {out_model}")
    elif last_pt.exists():
        shutil.copy(last_pt, out_model)
        print(f"\n✓ 最终模型已保存: {out_model}")

    # ── 打印指标 ───────────────────────────────────────────────────────
    if results and hasattr(results, "box"):
        map50  = getattr(results.box, "map50", None) or 0
        map5095 = getattr(results.box, "map", None) or 0
        print(f"\n{'='*50}")
        print(f"  训练完成！")
        print(f"  mAP@0.5  : {map50:.4f}")
        print(f"  mAP@0.5-0.95: {map5095:.4f}")
        print(f"  模型路径  : {out_model}")
        print(f"{'='*50}")

    return out_model


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="训练文档布局检测 YOLO 模型",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例：
  # 直接训练（数据放在默认目录）
  python scripts/train_yolo.py --epochs 100

  # 指定数据和参数
  python scripts/train_yolo.py \\
      --data-dir ./data/yolo_dataset \\
      --epochs 100 --batch 16 --model-size m

  # 通过 run_tmux.py 后台训练（>5分钟必须用 tmux）
  python scripts/run_tmux.py train --epochs 100 --batch 16
        """
    )
    parser.add_argument("--data-dir", type=str,
                        default=str(ROOT / "data" / "yolo_dataset"),
                        help="YOLO 数据集根目录")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--model-size", type=str, default="m",
                        choices=["n", "s", "m", "l", "x"],
                        help="YOLOv8 模型大小（n=最小，x=最大）")
    parser.add_argument("--resume", type=str, default=None,
                        help="从检查点恢复训练")
    parser.add_argument("--check-only", action="store_true",
                        help="仅检查依赖，不训练")

    args = parser.parse_args()

    # 1. 检查依赖
    check_dependencies()

    if args.check_only:
        print("✓ 依赖检查通过")
        return

    # 2. 准备数据集
    data_root = Path(args.data_dir).expanduser().resolve()
    data_yaml = prepare_dataset(data_root)

    # 3. 训练
    out = train(
        data_yaml=str(data_yaml),
        model_size=args.model_size,
        epochs=args.epochs,
        batch=args.batch,
        resume_path=args.resume,
    )
    print(f"\n训练完成，模型: {out}")


if __name__ == "__main__":
    main()
